### ISSUE TITLE
Disable localStorage to prevent error

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/tiddlywiki-whiteboard#27]
Error in electron

```js
boot.js:214 Error executing boot module $:/plugins/linonetwo/tw-whiteboard/widget.js: SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at loadUserPreferences (tidgi://3FqnQbuAVq1umrdT0d6JK/$:/plugins/linonetwo/tw-whiteboard/widget.js:22:53916)
    at eval (tidgi://3FqnQbuAVq1umrdT0d6JK/$:/plugins/linonetwo/tw-whiteboard/widget.js:22:54029)
    at eval (tidgi://3FqnQbuAVq1umrdT0d6JK/$:/plugins/linonetwo/tw-whiteboard/widget.js:204:4)
    at $tw.utils.evalGlobal (tidgi://3FqnQbuAVq1umrdT0d6JK/$:/boot/boot.js:616:12)
    at $tw.modules.execute (tidgi://3FqnQbuAVq1umrdT0d6JK/$:/boot/boot.js:904:15)
    at require (tidgi://3FqnQbuAVq1umrdT0d6JK/$:/boot/boot.js:851:24)
    at whiteboardWidgetIIFE (tidgi://3FqnQbuAVq1umrdT0d6JK/$:/plugins/linonetwo/tw-whiteboard/widget-loader.js:1:174)
    at eval (tidgi://3FqnQbuAVq1umrdT0d6JK/$:/plugins/linonetwo/tw-whiteboard/widget-loader.js:1:295)
    at eval (tidgi://3FqnQbuAVq1umrdT0d6JK/$:/plugins/linonetwo/tw-whiteboard/widget-loader.js:2:4)
    at $tw.utils.evalGlobal (tidgi://3FqnQbuAVq1umrdT0d6JK/$:/boot/boot.js:616:12)
```

One solution is add `standard: true` to `registerSchemesAsPrivileged` as https://www.electronjs.org/docs/latest/api/protocol#protocolregisterschemesasprivilegedcustomschemes said

> By default web storage apis (localStorage, sessionStorage, webSQL, indexedDB, cookies) are disabled for non standard schemes. So in general if you want to register a custom protocol to replace the http protocol, you have to register it as a standard scheme.

```
protocol.registerSchemesAsPrivileged([
  { scheme: 'http', privileges: { standard: true, bypassCSP: true, allowServiceWorkers: true, supportFetchAPI: true, corsEnabled: true, stream: true } },
  { scheme: 'https', privileges: { standard: true, bypassCSP: true, allowServiceWorkers: true, supportFetchAPI: true, corsEnabled: true, stream: true } },
  // don't use `standard: true,` otherwise it will prevents `protocol.handle` to work
  { scheme: 'tidgi', privileges: { bypassCSP: true, allowServiceWorkers: true, supportFetchAPI: true, corsEnabled: true, stream: true } },
```

but it does not work with `protocol.handle`

so have to disable localStorage here.

**Comment by linonetwo** [comment]
tidgi 已允许 localstorage，移动端还得看看，目前移动端会报错

**Comment by linonetwo** [comment]
都提供了
